version: "3.4"

services:
  mockerservice:
    image: mockerservice:latest
    container_name: mockerservice
    restart: always
    # depends_on:
    #   - mongo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8035:8035
    environment:
      MONGODB_URI: mongodb://mongo.docker:27017
      ONEAUTH_API_URL: https://api.ioak.io:8010
    networks:
      ioak-net:
        aliases:
          - mockerservice.docker

networks:
  ioak-net:
    name: ioak-network
